<?php
/** @var Banner $block */

use Magenest\Movie\Block\Widget\Banner;

?>
 <?php if ($block->getCustomerGroup() == "Is B2B") { ?>
<div class="widget block-banner">
    <div class="page-header services-page-header">
        <div><img style="width: 100%; height: 500px"
                  src="<?= $block->getViewFileUrl('Magenest_Movie::images/banner.jpg'); ?>" alt=""></div>
    </div>
</div>
<?php }?>


