<?php
/** @var Banner $block */

use Magenest\Movie\Block\Widget\Banner;

?>
<div class="widget block-banner">
    <div class="page-header services-page-header">
<!--        <h1 class="title">--><?php //= $block->escapeHtml($block->getData('title'));?><!--</h1>-->
<!--        <div class="subtitle">-->
<!--            <p>--><?php //= $block->escapeHtml($block->getData('subtitle'));?><!--</p>-->
<!--        </div>-->
        <div><img style="width: 100%; height: 500px" src="<?= $block->getViewFileUrl('Magenest_Movie::images/banner.jpg'); ?>" alt=""></div>
    </div>
</div>
