<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn $block
 */
$_order = $block->getOrder();
$_productOptions = $block->getItem()->getData('product_options');
?>
<?php if(isset($_productOptions['info_buyRequest']['example-date'])){?>
<span><?= /* @escapeNotVerified */ __($_productOptions['info_buyRequest']['example-date']) ?></span>
<?php } ?>
