<?php
/** @var ListProduct $block */

use Magenest\Movie\Block\Product\ListProduct;

$product = $block->getProduct();
?>
<?php $helper = $this->helper(\Magenest\Movie\Helper\Data::class); ?>
<?php $buttonTitle = $helper->getButtonTitle() ?>
<?php if ($product->isSaleable()): ?>
    <?php $postParams = $block->getAddToCartPostParams($product); ?>
    <div class="buynow-btn">
        <form action="<?= $block->escapeUrl($postParams['action']); ?>"
              id="product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
              method="post">
            <input type="hidden"
                   name="product"
                   value="<?= /* @noEscape */ $postParams['data']['product']; ?>">
            <input type="hidden"
                   name="uenc"
                   value="<?= /* @noEscape */ $postParams['data']['uenc']; ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <button type="submit"
                    title="<?= $block->escapeHtml(__($buttonTitle)) ?>"
                    class="action tocart buynow primary"
                    data-mage-init='
                    {
                        "Magenest_Movie/js/buy-now": {
                            "form": "#product_addtocart_form_<?= $block->escapeHtml($postParams['data']['product']) ?>"
                        }
                    }
                '>
                <span><?= $block->escapeHtml(__($buttonTitle)) ?></span>
            </button>
        </form>
    </div>
<?php endif; ?>
