<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Info $block */

use Magento\Customer\Block\Account\Dashboard\Info;

?>
<div class="block block-dashboard-info">
    <div class="block-content">
        <div class="box box-information">
            <div class="box-content">
                <p>
                <div class="field field-name-avatar">
                    <?php $avatarFile = !empty($block->getCustomer()->getCustomAttribute('profile_picture')) ? $block->getLayout()->createBlock('\Magenest\Movie\Block\Attributes\Avatar')->checkImageFile(base64_encode($block->getCustomer()->getCustomAttribute('profile_picture')->getValue())) : false; ?>
                    <?php $avatar = ($avatarFile) ? $block->getUrl('viewfile/avatar/view/', ['image' => base64_encode($block->getCustomer()->getCustomAttribute('profile_picture')->getValue())]) : $block->getViewFileUrl('Magenest_Movie::images/no-profile-photo.jpg'); ?>
                    <label class="label" for="profile_picture">
                        <img src="<?php echo $avatar; ?>" width="150px" height="150px" alt="profile-picture"
                             title="<?php echo __('Upload new avatar'); ?>" class="profile-image" id="profile-image"/>
                    </label>
                </div>
                <?= $block->escapeHtml($block->getName()) ?><br>
                <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                <?= $block->getCustomer()->getAddresses()[0]->getTelephone() ?><br>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
        </div>
    </div>
</div>
