<?php

/**
 * @var Magenest\Movie\Block\Display $block
 */
?>


<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

</style>
<h2>Table Movie</h2>
<table>
    <tr>
        <th class="Movie-id">Id</th>
        <th class="Movie-name">Movie Name</th>
    </tr>
    <?php
    foreach ($block->getMovieCollection() as $key => $movie) {
        echo '<tr>
                    <td>' . $movie->getActorId() . '</td>
                    <td>' . $movie->getName() . '</td>
                  </tr>';
    }
    ?>
</table>

    </br>
    </br>
<h2>Table Director</h2>
<table>
    <tr>
        <th class="Director-id">Id</th>
        <th class="Director-name">Director Name</th>
    </tr>
    <?php
    foreach ($block->getDirectorCollection() as $key => $director) {
        echo '<tr>
                    <td>' . $director->getDirectorId() . '</td>
                    <td>' . $director->getName() . '</td>
                  </tr>';
    }
    ?>
</table>

</br>
</br>

<h2>Table Actor</h2>

<table>
    <tr>
        <th class="Actor-id">Id</th>
        <th class="Actor-name">Actor Name</th>
    </tr>
    <?php
    foreach ($block->getActorCollection() as $key => $actor) {
        echo '<tr>
                    <td>' . $actor->getActorId() . '</td>
                    <td>' . $actor->getName() . '</td>
                  </tr>';
    }
    ?>
</table>


</body>
</html>
